add new components and router
disha1010/sport-store pull request #2
Opened 2017-05-10 08:46 UTC by disha1010

add new components Sidebar, List, Details
add routing for different pages
add styles

2017-05-10 11:05 UTC, imevro requested changes
В целом норм

2017-05-10 11:05 UTC, imevro commented on src/App.js
Лучше сначала именованные импорты, а потом обычные.

```
import Sidebar;
import List;
import './style.css';
```

2017-05-10 11:05 UTC, imevro commented on src/App.js
Ссылки должны быть в snake-case и обозначать принадлежность: `/items`, `/item/1`

2017-05-10 11:05 UTC, evgenyrodionov commented on src/Details.js
> +import bitmap_slide from './img/bitmap_slide.png'
Все импорты-экспорты в `camelCase` и назвать лучше `product-image-1.png`

2017-05-10 11:05 UTC, evgenyrodionov commented on src/List.js
> +import {Link} from 'react-router-dom'
Импорты из нпм-пакетов должны быть раньше чем импорты локальных файлов

2017-05-10 11:05 UTC, evgenyrodionov commented on src/List.js
> +import filter from './img/filter.png'
Мешаешь двойные кавычки и одинарные

2017-05-10 11:05 UTC, evgenyrodionov commented on src/List.js
> +            <div className="item">
Попробуй карточку вынести в компонент

2017-05-10 11:05 UTC, evgenyrodionov commented on src/Sidebar.js
> +              <g fill="#FFF" fill-rule="evenodd">
fill-rule → fillRule

2017-05-11 09:50 UTC, imevro requested changes
Нормас, но нужны фиксы

2017-05-11 09:50 UTC, evgenyrodionov commented on src/Details.js
> +import itemPicFull from './img/item-pic-full.png'
Сделай через require()

2017-05-11 09:50 UTC, evgenyrodionov commented on src/ItemCard.js
> +export default settings => {
Это не `settings`, это `props`

2017-05-11 09:50 UTC, evgenyrodionov commented on src/ItemCard.js
> +  var banner;
Вары — нет, есть const

2017-05-11 09:50 UTC, evgenyrodionov commented on src/ItemCard.js
> +  }
Попробуй подключить библиотеку `classnames`, получше будет

2017-05-11 09:50 UTC, evgenyrodionov commented on src/ItemCard.js
> +  if (settings.showSaleBage == true) {
Но тут достаточно просто `if (props.showSaleBadge)`

2017-05-11 09:50 UTC, evgenyrodionov commented on src/ItemCard.js
> +    <div className="col-md-4">
Сетку лучше не выносить в компонент

2017-05-11 09:50 UTC, evgenyrodionov commented on src/List.js
> +import ItemFilter from './ItemFilter'
А зачем Item

2017-05-11 21:27 UTC, imevro requested changes
Норм, но немного с неймингом проблемы

2017-05-11 21:27 UTC, evgenyrodionov commented on package.json
> +    "css-loader": "^0.28.1",
Хм, зачем

2017-05-11 21:27 UTC, evgenyrodionov commented on package.json
> +    "style-loader": "^0.17.0"
И это тоже

2017-05-11 21:27 UTC, evgenyrodionov commented on src/App.js
> +          <Route exact path="/shoes" component={List} />
Можно убрать)

2017-05-11 21:27 UTC, evgenyrodionov commented on src/Details/Properties.js
> +import React from "react";
Это скорее Info

2017-05-11 21:27 UTC, evgenyrodionov commented on src/List/Card.js
> +  const linkTo = props.link ? "/shoe" : "#";
1) props.link → to
2) от этой проверки можно избавиться, сразу в Link передавай props.to

2017-05-11 21:27 UTC, evgenyrodionov commented on src/List/Card.js
> +  const banner = props.showSaleBage
Если используешь булеан, то лучше префиксуй их через is: isOnSale, например

2017-05-11 21:27 UTC, evgenyrodionov commented on src/Sidebar/Menu.js
> +            <svg
Засунь в компонент

2017-05-11 21:27 UTC, evgenyrodionov commented on src/Sidebar/Menu.js
> +            <svg
иконка типа

2017-05-11 21:27 UTC, evgenyrodionov commented on src/index.js
> +import "./flexboxgrid.css";
Из нпма же ставишь?

2017-05-12 16:15 UTC, disha1010 commented on package.json
> +    "style-loader": "^0.17.0"
думала нужно для sc, но потом поняла, что нет. Не удалила просто

2017-05-12 17:45 UTC, imevro approved these changes
Норм. Бей на компоненты.

2017-05-12 17:45 UTC, evgenyrodionov commented on src/BannerOnSale.js
> +import React from "react";
Это лейбл, не баннер

2017-05-12 17:45 UTC, merged