use styled-components everywhere
disha1010/sport-store pull request #7
Opened 2017-05-15 19:49 UTC by disha1010

2017-05-15 21:27 UTC, imevro requested changes
↓

2017-05-15 21:27 UTC, evgenyrodionov commented on package.json
> +    "lint": "eslint src --ext=js,jsx --fix",
Нет

2017-05-15 21:27 UTC, evgenyrodionov commented on package.json
> +    "lint": "eslint src --ext=js,jsx --fix",
Только руками вызывать

2017-05-15 21:27 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +      <Cost {...props}>{props.cost}$</Cost>
Нет, только руками передавать нужные пропсы

2017-05-15 21:27 UTC, evgenyrodionov commented on src/styled.js
> +/* eslint-disable no-unused-expressions */
Нет, сделай обычный цсс и импортни в апп джс или индекс.жс, не нужно увлекаться инструментами

2017-05-18 18:57 UTC, disha1010 commented on package.json
> +    "lint": "eslint src --ext=js,jsx --fix",
сделал

2017-05-18 18:57 UTC, disha1010 commented on src/Products/List/Card.jsx
> +      <Cost {...props}>{props.cost}$</Cost>
сделал

2017-05-18 18:57 UTC, disha1010 commented on src/styled.js
> +/* eslint-disable no-unused-expressions */
сделал

2017-05-19 09:29 UTC, imevro requested changes
Норм, но ↓

2017-05-19 09:29 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        <Col sm={6} md={4} lg={4}>
Можно убрать lg={4}, потому что если у тебя стоит md={4}, то оно так и будет пока ты не переопределишь

2017-05-19 09:29 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        <Col sm={6} md={4} lg={4}>
MOBILE FIRST!

2017-05-19 09:29 UTC, evgenyrodionov commented on src/Products/Show/Gallery/index.jsx
> +    <MoreImages>
Thumbnails?

2017-05-19 09:29 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +      <ButtonColor theme={gray} />
Сделай проще:
```jsx
const gray = '#e0e0e0';

<ColorButton color={gray} />
```

2017-05-19 09:31 UTC, imevro requested changes
И ещё ↓

2017-05-19 09:31 UTC, evgenyrodionov commented on src/LabelOnSale/styled.js
> +  @media screen and (max-width: 414px) {
А, ещё тут хуёво: во-первых, сделай миксин

2017-05-19 09:31 UTC, evgenyrodionov commented on src/LabelOnSale/styled.js
> +    position: ${props => (props.isDetails ? 'static' : 'absolute')};
Во-вторых: нет, так нельзя делать. Это плохой подход. Компонент вообще не должен ничего знать о том, где он используется, поэтому убирай позишн, убирай марджин-топ и используй как

```jsx
const CardLabel = styled(Label)`
  position: absolute;
  margin-top: 10px;
`
```

2017-05-21 09:35 UTC, imevro requested changes
Проблемы с адаптивом — пересмотри про mobile first часть

Я не стал везде комментировать, много мест, но max-width это неправильно

2017-05-21 09:35 UTC, evgenyrodionov commented on src/ProductLabel.js
> +  @media screen and (max-width: 414px) {
Пересмотри видео про адаптив и часть про mobile first, у тебя плохое условие тут

2017-05-21 09:35 UTC, evgenyrodionov commented on src/Products/List/styled.js
> +  height: 120.5px;
1) 120.5 ад
2) убери explicitly задание высоты, она должна сама вычислиться через паддинги и прочее

2017-05-21 09:35 UTC, evgenyrodionov commented on src/Products/List/styled.js
> +  @media screen and (max-width: 2114px) {
?

2017-05-21 09:35 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +        {this.state.entries.map(menuItem => <Submenu key={menuItem} menuTitle={menuItem} />)}
Нет, убери конфигурацию, это зло
Напиши нормально декларативно

2017-05-21 09:35 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +    <Search value={props.location.pathname === '/shoe' ? 'ultra boost' : ''} />
Хорошая идея, но выкинь)

2017-05-21 10:02 UTC, disha1010 commented on src/Products/List/styled.js
> +  @media screen and (max-width: 2114px) {
позже исправлю

2017-05-21 10:02 UTC, disha1010 commented on src/ProductLabel.js
> +  @media screen and (max-width: 414px) {
позже исправлю

2017-05-22 19:09 UTC, imevro requested changes
Фикси

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Products/List/Filter/Sizes/styled.js
> +  width: 254px;
Без фикс ширины

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        <Col xs={12} sm={6} md={4}>
По-умолчанию и так 12

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Products/List/styled.js
> +    left: 327px;
Плохо, убирай, не должно быть позишена у основного контента

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +          <ButtonColor color={gray} onClick={() => this.selectColor(gray)} />
Засунь в массив и сделай мап

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/Menu/Submenu/index.jsx
> +          {submenuTitle}
Вытащи из константы, сделай прямо здесь

И убери див

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/Menu/Submenu/index.jsx
> +          {submenuTitle}
И сделай нормальный нейминг, в журналист есть пример

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/Menu/Submenu/index.jsx
> +      <div className="submenu">
Откуда класснейм, если у нас стайлед компонентс?

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/Menu/Submenu/index.jsx
> +  toggleState() {
toggle

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/Menu/Submenu/index.jsx
> +    this.setState({ isOpened: !this.state.isOpened });
https://medium.freecodecamp.com/functional-setstate-is-the-future-of-react-374f30401b6b
https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +    <Submenu menuTitle="sports" />
Компонент и так называется меню, зачем в пропах префикс меню?

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +    <Submenu menuTitle="brands" />
Само меню нужно переделать, в журналист расписано как

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +import { withRouter } from 'react-router';
Убери

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +import { withRouter } from 'react-router';
Зачем оно

2017-05-22 19:09 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +import { withRouter } from 'react-router';
Используй NavLink и activeClassname

2017-05-24 11:47 UTC, imevro requested changes

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +    <Submenu title="football" />
В журналист описано как, это неправильно

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Sidebar/Menu/Submenu.jsx
> +            <StyledLink to={{ pathname: `/${this.props.title}/shoes` }}>shoes</StyledLink>
Выноси ссылки отсюда в сайдбар

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Sidebar/Menu/Submenu.jsx
> +            <StyledLink to={{ pathname: `/${this.props.title}/shoes` }}>shoes</StyledLink>
Можно обычной строкой, а не объектом

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +      selectedColor: gray,
color

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +    const infoColor = colors.map(colorType => (
1) colors, потому что множественное число

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +    const infoColor = colors.map(colorType => (
2) убирай эту константу, делай мап прямо там где надо

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +    const infoColor = colors.map(colorType => (
3. colorType? Почему не просто color?

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +  selectColor(color) {
handleChangeColor

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +  selectColor(color) {
Потому что ты ловишь эвент

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +        <Save>
Зачем этот лишний враппер?

2017-05-24 11:47 UTC, evgenyrodionov commented on src/Products/Show/Gallery/index.jsx
> +      selectedImg: itemPicFull1,
Вынеси список картинок в константу images и храни в стейте индекс выбранной пикчи

2017-05-24 13:41 UTC, disha1010 commented on src/Products/Show/Info.jsx
> +    const infoColor = colors.map(colorType => (
сделала

2017-05-24 13:41 UTC, disha1010 commented on src/Products/Show/Info.jsx
> +  selectColor(color) {
сделал

2017-05-24 13:42 UTC, disha1010 commented on src/Products/Show/Info.jsx
> +      selectedColor: gray,
сделал

2017-05-24 13:44 UTC, disha1010 commented on src/Products/Show/Gallery/index.jsx
> +      selectedImg: itemPicFull1,
сделал

2017-05-24 21:13 UTC, imevro requested changes

2017-05-24 21:13 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +SideBar.propTypes = {
зач

2017-05-24 21:13 UTC, evgenyrodionov commented on src/Sidebar/Search/index.jsx
> +export const SearchInput = props => (
зачем экспортить SearchInput и ещё его потом дефолтно?

2017-05-24 21:13 UTC, evgenyrodionov commented on src/Sidebar/Menu/styled.js
> +export const Title = styled.div`
Это кнопка

2017-05-24 21:13 UTC, evgenyrodionov commented on src/Products/Show/Info.jsx
> +      color: colors[0],
храни индекс, а не значение

2017-05-24 21:13 UTC, evgenyrodionov commented on src/Products/Show/Gallery/index.jsx
> +  { preview: itemPic1, full: itemPicFull1 },
С этим красава

2017-05-24 21:13 UTC, evgenyrodionov commented on src/Products/Show/Gallery/index.jsx
> +      selectedImgId: 0,
Это индекс, не айди

2017-05-25 21:07 UTC, imevro requested changes

2017-05-25 21:07 UTC, evgenyrodionov commented on src/App.jsx
> +      <Route exact path="/:category/:subCategory" component={List} />
/products/:category/:subCategory

2017-05-25 21:07 UTC, evgenyrodionov commented on src/App.jsx
> +      <Route exact path="/:category/:subCategory/:itemId" component={Show} />
productId соот-но

2017-05-25 21:07 UTC, evgenyrodionov commented on src/Products/List/Filter/Icon/index.jsx
>    <Wrapper>
А зачем враппер, если у тебя есть иконка?

2017-05-25 21:07 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +            to={'/running/shoes/1'}
Если это статичная строка, то почему не to="", а to={''}?

2017-05-25 21:07 UTC, evgenyrodionov commented on src/Products/Show/Gallery/index.jsx
> +  selectImg(imageIndex) {
Если проименуешь также как ключ объекта (selectedImgIndex), то сможешь воспользоваться object shorthand

2017-05-25 21:07 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +        <Title onClick={this.toggle}>
Это кнопка, не заголовок

2017-05-26 09:18 UTC, merged